# Builds the two Fab submission zips without local/generated folders.
#
#   powershell -ExecutionPolicy Bypass -File Tools\PackageForFab.ps1 [-OutDir D:\FabUpload]
#
#   DynamicSplitScreen_Plugin.zip          -> the plugin (Source, Content, Config, .uplugin)
#   DynamicSplitScreen_ExampleProject.zip  -> the example project (with the plugin inside)

param(
    [string]$OutDir = (Join-Path $PSScriptRoot "..\..\DynamicSplitScreen_FabUpload")
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$OutDir = [System.IO.Path]::GetFullPath($OutDir)
$Staging = Join-Path $OutDir "_staging"

# Never shipped: generated by the editor / compiler / IDE, or developer-only
$ExcludeDirs = @("Binaries", "Intermediate", "Saved", "Build", "DerivedDataCache", ".vs", ".git", ".idea", "Developers", "Collections")
$ExcludeFiles = @("*.sln", "*.suo", "*.VC.db", "*.opensdf", "*.sdf", ".vsconfig")

function Copy-Clean([string]$From, [string]$To, [string[]]$ExtraDirs = @()) {
    $dirs = $ExcludeDirs + $ExtraDirs
    robocopy $From $To /E /NFL /NDL /NJH /NJS /NP /XD $dirs /XF $ExcludeFiles | Out-Null
    if ($LASTEXITCODE -ge 8) { throw "robocopy failed ($LASTEXITCODE): $From" }
}

function Assert-Clean([string]$Root) {
    $bad = Get-ChildItem $Root -Recurse -Directory | Where-Object { $ExcludeDirs -contains $_.Name }
    if ($bad) { throw "Excluded folders found in package: $($bad.FullName -join ', ')" }
}

if (Test-Path $Staging) { Remove-Item $Staging -Recurse -Force }
New-Item -ItemType Directory -Force -Path $Staging | Out-Null

# ── Plugin ──
$PluginStage = Join-Path $Staging "Plugin\DynamicSplitScreen"
Copy-Clean (Join-Path $ProjectRoot "Plugins\DynamicSplitScreen") $PluginStage
Assert-Clean $PluginStage
$PluginZip = Join-Path $OutDir "DynamicSplitScreen_Plugin.zip"
if (Test-Path $PluginZip) { Remove-Item $PluginZip -Force }
Compress-Archive -Path $PluginStage -DestinationPath $PluginZip

# ── Example project ──
$ProjectStage = Join-Path $Staging "Project\DynamicSplitScreenExample"
Copy-Clean $ProjectRoot $ProjectStage @("Tools", "Docs")
Assert-Clean $ProjectStage

# Editor-only experimental MCP plugins are a local dev convenience; they are not part of the product
$DevOnlyPlugins = @("ModelContextProtocol", "MCPClientToolset", "AllToolsets")
$UProjectPath = Join-Path $ProjectStage "SplitScreen.uproject"
$UProject = Get-Content $UProjectPath -Raw | ConvertFrom-Json
$UProject.Plugins = @($UProject.Plugins | Where-Object { $DevOnlyPlugins -notcontains $_.Name })
$UProject | ConvertTo-Json -Depth 10 | Set-Content $UProjectPath -Encoding utf8
$ProjectZip = Join-Path $OutDir "DynamicSplitScreen_ExampleProject.zip"
if (Test-Path $ProjectZip) { Remove-Item $ProjectZip -Force }
Compress-Archive -Path $ProjectStage -DestinationPath $ProjectZip

Remove-Item $Staging -Recurse -Force

Get-ChildItem $OutDir -Filter *.zip | ForEach-Object { "{0}  {1:N1} MB" -f $_.FullName, ($_.Length / 1MB) }
