# Builds the Fab submission zips without local/generated folders.
#
#   powershell -ExecutionPolicy Bypass -File Tools\PackageForFab.ps1 [-OutDir D:\FabUpload] [-IncludePlugin]
#
#   DynamicSplitScreen_Plugin.zip          -> the plugin (Source, Content, Config, .uplugin) for the Fab upload
#   DynamicSplitScreen_ExampleProject.zip  -> the example project. Without -IncludePlugin the plugin is left out:
#                                             users install it from Fab into the engine first (it is a paid product).

param(
    [string]$OutDir = (Join-Path $PSScriptRoot "..\..\DynamicSplitScreen_FabUpload"),
    [switch]$IncludePlugin
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$OutDir = [System.IO.Path]::GetFullPath($OutDir)
$Staging = Join-Path $OutDir "_staging"

# Never shipped: generated by the editor / compiler / IDE, or developer-only
$ExcludeDirs = @("Binaries", "Intermediate", "Saved", "Build", "DerivedDataCache", ".vs", ".git", ".idea", "Developers", "Collections")
$ExcludeFiles = @("*.sln", "*.suo", "*.VC.db", "*.opensdf", "*.sdf", ".vsconfig")

function Copy-Clean([string]$From, [string]$To, [string[]]$ExtraDirs = @()) {
    $dirs = $ExcludeDirs + $ExtraDirs
    robocopy $From $To /E /NFL /NDL /NJH /NJS /NP /XD $dirs /XF $ExcludeFiles | Out-Null
    if ($LASTEXITCODE -ge 8) { throw "robocopy failed ($LASTEXITCODE): $From" }
}

function Assert-Clean([string]$Root) {
    $bad = Get-ChildItem $Root -Recurse -Directory | Where-Object { $ExcludeDirs -contains $_.Name }
    if ($bad) { throw "Excluded folders found in package: $($bad.FullName -join ', ')" }
}

function New-Zip([string]$Source, [string]$Zip) {
    if (Test-Path $Zip) { Remove-Item $Zip -Force }
    Compress-Archive -Path $Source -DestinationPath $Zip
}

if (Test-Path $Staging) { Remove-Item $Staging -Recurse -Force }
New-Item -ItemType Directory -Force -Path $Staging | Out-Null

# ── Plugin ──
$PluginSource = Join-Path $ProjectRoot "Plugins\DynamicSplitScreen"
$PluginStage = Join-Path $Staging "Plugin\DynamicSplitScreen"
Copy-Clean $PluginSource $PluginStage
Assert-Clean $PluginStage
New-Zip $PluginStage (Join-Path $OutDir "DynamicSplitScreen_Plugin.zip")

# ── Example project ──
$ProjectStage = Join-Path $Staging "Project\DynamicSplitScreenExample"
$ProjectExtra = @((Join-Path $ProjectRoot "Tools"), (Join-Path $ProjectRoot "Docs"))
if (-not $IncludePlugin) { $ProjectExtra += $PluginSource }
Copy-Clean $ProjectRoot $ProjectStage $ProjectExtra
Assert-Clean $ProjectStage
if (-not $IncludePlugin -and (Test-Path (Join-Path $ProjectStage "Plugins\DynamicSplitScreen"))) { throw "Plugin was not excluded" }

# Editor-only experimental MCP plugins are a local dev convenience; they are not part of the product
$DevOnlyPlugins = @("ModelContextProtocol", "MCPClientToolset", "AllToolsets")
$UProjectPath = Join-Path $ProjectStage "SplitScreen.uproject"
$UProject = Get-Content $UProjectPath -Raw | ConvertFrom-Json
$UProject.Plugins = @($UProject.Plugins | Where-Object { $DevOnlyPlugins -notcontains $_.Name })
[System.IO.File]::WriteAllText($UProjectPath, ($UProject | ConvertTo-Json -Depth 10), (New-Object System.Text.UTF8Encoding $false))
New-Zip $ProjectStage (Join-Path $OutDir "DynamicSplitScreen_ExampleProject.zip")

Remove-Item $Staging -Recurse -Force

Get-ChildItem $OutDir -Filter *.zip | ForEach-Object { "{0}  {1:N1} MB" -f $_.FullName, ($_.Length / 1MB) }
